cleaned up

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,9 +2,9 @@
 . "$(dirname "$0")/_/husky.sh"
 
 # Check Prettier standards
-npm run format ||
+npm run check-format ||
 (
-    echo 'Prettier check-format check failed';
+    echo 'Prettier format check failed';
     false;
 )
 
